name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: AWS Deploy S3
        # You may pin to the exact commit or the version.
        # uses: oneyedev/aws-deploy-s3@16e61e78e12904502d31e6c4adbe1f7d58eddaa7
        uses: oneyedev/aws-deploy-s3@v2
        with:
          # AWS Region of S3 Bucket
          region: ew-west-1
          # Name of S3 Bucket
          bucket: www.looplend.it
          # A Local Source Directory to Upload
          source: ./
          # A Remote Target Directory to Upload
          target: ./
