name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: reggionick/s3-deploy@v3
        name: Upload on S3
        with:
          folder: .
          bucket: www.looplend.it
          bucket-region: eu-west-1
